services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    networks:
      - queue-monitoring
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USERNAME:-rabbitmq}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD:-rabbitmq}
    ports:
      - ${AMQP_PORT:-5672}:5672
      - ${MQ_UI_PORT:-15672}:15672
    restart: unless-stopped

  python:
    build:
      dockerfile: ./python/Dockerfile
      context: ./
    depends_on:
      - rabbitmq
    env_file: .env
    networks:
      - queue-monitoring
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    restart: unless-stopped
      
  api:
    build:
      dockerfile: ./api/Dockerfile
      context: ./
    depends_on:
      - rabbitmq
    networks:
      - queue-monitoring
    volumes:
      - ./api:/app
    env_file: .env
    ports:
      - ${API_PORT:-8888}:80
    restart: unless-stopped

  dashboard:
    build:
      dockerfile: ./web/Dockerfile
      context: ./
    depends_on:
      - api
    volumes:
      - ./web:/app
    networks:
      - queue-monitoring
    ports:
      - ${DASHBOARD_PORT:-5173}:5173
    restart: unless-stopped

networks:
  queue-monitoring:
